baseURL = "https://example.org/"
languageCode = "en-us"
title = "drishtikon"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\\[', '\\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


[params]
    # Uncomment if you have a logo image
    # logo = "/images/logo.png"

    # Profile section for homepage
    profilePhoto = "/images/pfp.jpg"
    profileDescription = """Welcome to drishtikon (*perspective*). Stay a while! Drishtikon is a simple, minimal, [Hugo](https://gohugo.io/) theme that takes inspiration from Andrew Hwan Park's [Brutalist Blog](https://hw4n.com/brutalist-blog/) and Tyler McRobert's [Bridget](https://tylermcrobert.com/bridget-baker). Additionally, this theme uses the [Inter](https://rsms.me/inter/) typeface originally developed by Rasmus Andersson."""
    github = "https://github.com/yourusername"
    email = "mailto:your.email@example.com"
    math = true

[menu]
    [[menu.main]]
        name = "posts"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        name = "writings"
        url = "/writings/"
        weight = 20
    [[menu.main]]
        name = "photos"
        url = "/photos/"
        weight = 30


